### PR TITLE
fix(doors): update event for doorlock v2

### PR DESCRIPTION
**Pull request by BerkieBb**

### CODE REVIEW

**Comment by izMystic** [comment]
Wouldnt the doorIDs need changing, as theyre sorted differently?
\

**Comment by BerkieBb** [comment]
iirc, they're not sorted differently

**Comment by IKKaybe** [comment]
Manually implemented this update and the doors dont seem to work for me.

**Comment by BerkieBb** [comment]
I know, I need to update the door id's

**Comment by SharkyFP** [comment]
Any luck found ?

**Comment by BerkieBb** [comment]
The ids should be good now

**Comment by IllInuz** [comment]
Checked, verified working.

**Review by deandum — APPROVED** [review]

**Pull request merged**
