### PR TITLE
Added locales and danish translation

### PR DESCRIPTION
**Pull request by ThunderScripts**

### CODE REVIEW

**Review by ItsANoBrainer — APPROVED** [review]

**Comment by GhzGarage** [comment]
Doubt you wanna update this but if you do please let me know

**Comment by ThunderScripts** [comment]
it should be updated now

**Comment by Andyauk** [comment]
> it should be updated now

branch still has conflicts, hope it gets sorted, as the live version is very buggy. so would be interesting to see if things are slightly better here.

**Comment by BerkieBb** [comment]
Still has conflicts

**Comment by BerkieBb** [comment]
Closing for inactivity

**Pull request closed without merging**
